### ISSUE TITLE
"Set as login page" new icon

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/ux#1]
As a part of the Resource finding issue, we want to expose the action called "Set as login page" currently under the topbar's kebab menu:

![image](https://github.com/user-attachments/assets/f3945327-bc74-4fb1-98e2-b5f3f6274053)

The new location would be near the title of each page.

![image](https://github.com/user-attachments/assets/0d0ee7c2-f590-4fc8-b167-6639de540744)

The current icon is a placeholder, the new icon will replace it:

![image](https://github.com/user-attachments/assets/bf49f5ab-9c53-4a02-b981-73d4b54bfbd6)

**Comment by anatrofimenko** [comment]
![Image](https://github.com/user-attachments/assets/0e4b5108-d070-4870-bca8-bb8e598d68a0)

**Comment by anatrofimenko** [comment]
The icon in in the Design System file in Figma
